title: tokenfiend
description: "A blog where I try out llms"
lang: en-US
timezone: America/New_York
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tokenfiend.com" # your site URL

# Remote theme
remote_theme: piharpi/jekyll-klise

# Site version (auto-updated by git hook)
version: "1.0.1"

# Author information
author:
  name: Tokenfiend
  bio: "Writing about LLMs and my opinions on them"
  username: tokenfiend
  avatar: /assets/img/avatar.jpg # this will be prefixed with baseurl automatically
  email: your-email@email.com
  github: tokenfiend

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Pagination
paginate: 5
paginate_path: "/page/:num"

# Plugins (all GitHub Pages supported)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# SASS
sass:
  style: compressed

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
